language: java

sudo: false

notifications:
  email:
    # Group email notifications are disabled for now, since we cannot do it on a per-branch basis.
    # Right now, it would trigger a notification for each fork, which generates a lot of spam.
    # recipients:
    #  - dataflow-sdk-build-notifications+travis@google.com
    on_success: change
    on_failure: always

matrix:
  include:
    # On OSX, run with default JDK only.
    - os: osx
    # On Linux, run with specific JDKs only.
    - os: linux
      env: CUSTOM_JDK="oraclejdk8"
    # The distribution does not build with Java 7 by design. We need to rewrite these tests
    # to, for example, build and install with Java 8 and then test examples with Java 7.
    # - os: linux
    #   env: CUSTOM_JDK="oraclejdk7"
    # - os: linux
    #  env: CUSTOM_JDK="openjdk7"

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then jdk_switcher use "$CUSTOM_JDK"; fi

install:
  - travis_retry mvn install clean -U -DskipTests=true

script:
  - travis_retry mvn install -U
